import type { Metadata } from "next";
import { Lato } from "next/font/google";
import i18nConfig from '@/i18n-config';
import './globals.css';

const lato = Lato({ weight: ['300', '400'], subsets: ['latin', 'latin-ext'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale: string) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: string;
  }
}>) {
  return (
    <html lang={locale}>
      <body className={lato.className}>{children}</body>
    </html>
  );
}
